CREATE TABLE user_account (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(100) NOT NULL UNIQUE,
    password_hash   VARCHAR(255) NOT NULL,
    email           VARCHAR(254) NOT NULL UNIQUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE tower_account (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_account_id  INTEGER NOT NULL,
    tower_id         VARCHAR(16),
    tower_nickname   VARCHAR(255) NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_tower_account_user
       FOREIGN KEY (user_account_id)
           REFERENCES user_account(id)
           ON DELETE CASCADE,

    CONSTRAINT uq_tower_account_user_tower
       UNIQUE (user_account_id, tower_id)
);